name: acme

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  acme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: acmesh-official/acme.sh
      - name: "Use Let's Encrypt"
        run: |
          mkdir -p tmp
          ./acme.sh --home tmp --set-default-ca --server letsencrypt
      - name: "Issue certificates"
        env:
          CF_Account_ID: ${{ secrets.CF_Account_ID }}
          CF_Token: ${{ secrets.CF_Token }}
        run: |
          ./acme.sh --home tmp --issue --dns dns_cf -d '*.t.isucon.pw'
      - name: "Populate certificates"
        run: |
          cp ./tmp/\*.t.isucon.pw_ecc/\*.t.isucon.pw.cer cert.pem
          cp ./tmp/\*.t.isucon.pw_ecc/fullchain.cer fullchain.pem
          cp ./tmp/\*.t.isucon.pw_ecc/\*.t.isucon.pw.key key.pem
      - name: "Get timestamp"
        run: |
          echo "TIMESTAMP=$(date +'%Y%m%d%H%M%S')" >> "$GITHUB_ENV"
      - name: "Release certificates"
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TIMESTAMP }}
          files: |
            cert.pem
            fullchain.pem
            key.pem
